import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, recall_score, precision_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# 1. Load the anonymized dataset
# df = pd.read_csv("../folktables_travel_time_RAW.csv")
df = pd.read_csv("travel_time_k=10.csv")  # Load the anonymized dataset generated by Anjana

# Clean up the index column if pandas saved it automatically


# 2. Define your target (label) column. 
TARGET_COLUMN = "JWMNP" 

features_to_encode = [col for col in df.columns if col != TARGET_COLUMN]
df[features_to_encode] = df[features_to_encode].astype(str)

# 3. Separate features (X) and the label (y)
X = df.drop(columns=[TARGET_COLUMN])
y = df[TARGET_COLUMN]

# If you need the 'RAC1P' column for fairness groups later, you can extract it here.
# Otherwise, we just split X and y.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

# 4. Preprocessing: We must One-Hot-Encode the generalized string ranges from Anjana
# and Scale any remaining numeric columns.
categorical_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()
numeric_cols = X.select_dtypes(exclude=['object', 'category']).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ])

# 5. Build the pipeline (added max_iter=1000 so LogisticRegression doesn't time out)
model = make_pipeline(preprocessor, LogisticRegression(max_iter=1000))

# 6. Train the model
model.fit(X_train, y_train)

# 7. Predict and Evaluate
yhat = model.predict(X_test)
accuracy = accuracy_score(y_test, yhat)
print(f"accuracy: {accuracy}")
print(f"f1 score:  {f1_score(y_test, yhat)}")
print(f"precision score: {precision_score(y_test, yhat)}")
print(f"recall score:  {recall_score(y_test, yhat)}")
